---
title: "Audrey Dissertation Analysis"
author: "Audrey Nelson"
date: "May 12, 2016"
output: word_document
---

```{r libraries and read-in, echo = FALSE, message = FALSE, warning = FALSE}
# library(foreign)
library(memisc)
library(reshape2)
library(plyr)
library(dplyr)
library(ggplot2)
library(pander)
df <- as.data.set(spss.system.file("./Data/College coping data (complete).sav"))
df <- as.data.frame(df)
```

```{r exaine b and m, echo = FALSE, warning = FALSE}
#reshape to long form
df$ID <- rownames(df)
dfl <- melt(df, id = c("ID", "class", "ethnicity", "gender", "age"))

#just b and m

dfl.bm <- dfl[which(grepl("b|m", dfl$variable)), ]
dfl.bm$vartype <- gsub("^(\\w{1})\\d+$", "\\1", dfl.bm$variable)
# Sum over the two variable types
df.bm <- summarize(group_by(dfl.bm, ID, class, ethnicity, gender, age, vartype), total = sum(value))
#reshape to wide format
df.bm.w <- reshape(as.data.frame(df.bm), timevar = "vartype", times = c("b", "m"), idvar = c("ID", "class", "ethnicity", "gender", "age"), direction = "wide")

ggplot(df.bm.w, aes(x = total.b, y = total.m)) + geom_point() + geom_smooth()
```

Figure 1.  The relationship between the sum of b and the sum of m appears to be linear and positive.

```{r correlation b and m, echo = FALSE}
cbm <- cor(df.bm.w$total.b, df.bm.w$total.m, use = "pairwise.complete.obs")
```
The correlation between the sum of b and the sum of m for each participant is `r cbm`.


Table 1:  The results of a linear model predicting the sum of m from the sum of b showing a significant positive relationship.
```{r model m as a function of b, echo=FALSE}
m1 <- lm(total.m ~ total.b, data = df.bm.w)

sm1 <- summary(m1)
print(sm1)
```


```